/**
 * 파일 충돌 감지 및 방지 유틸리티
 * 기존 파일과의 충돌을 감지하고, 백업 및 경고 기능 제공
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'fs';
import { join, dirname, basename } from 'path';

export interface ConflictInfo {
  filePath: string;
  exists: boolean;
  hasUserModifications: boolean;
  originalContent?: string;
}

export interface WriteOptions {
  force?: boolean; // 기존 파일 덮어쓰기
  backup?: boolean; // 백업 생성
  backupDir?: string; // 백업 디렉토리
}

export interface WriteResult {
  written: boolean;
  filePath: string;
  backupPath?: string;
  skipped?: boolean;
  reason?: string;
}

// 자동 생성된 파일임을 나타내는 마커
const AUTO_GENERATED_MARKER = '// Auto-generated by bruno-api-typescript';
const DO_NOT_EDIT_WARNING = '// ⚠️ DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on regeneration';

/**
 * 파일에 자동 생성 마커가 있는지 확인
 */
export function hasAutoGeneratedMarker(content: string): boolean {
  return content.includes(AUTO_GENERATED_MARKER);
}

/**
 * 파일 내용에 자동 생성 마커 추가
 */
export function addAutoGeneratedMarker(content: string): string {
  const header = `${AUTO_GENERATED_MARKER}\n${DO_NOT_EDIT_WARNING}\n\n`;
  return header + content;
}

/**
 * 단일 파일 충돌 확인
 */
export function checkFileConflict(filePath: string): ConflictInfo {
  const exists = existsSync(filePath);
  let hasUserModifications = false;
  let originalContent: string | undefined;

  if (exists) {
    originalContent = readFileSync(filePath, 'utf-8');
    // 자동 생성 마커가 없으면 사용자가 수정한 것으로 간주
    hasUserModifications = !hasAutoGeneratedMarker(originalContent);
  }

  return {
    filePath,
    exists,
    hasUserModifications,
    originalContent,
  };
}

/**
 * 여러 파일의 충돌 확인
 */
export function checkMultipleConflicts(filePaths: string[]): ConflictInfo[] {
  return filePaths.map(checkFileConflict);
}

/**
 * 충돌하는 파일 목록 필터링
 */
export function getConflictingFiles(conflicts: ConflictInfo[]): ConflictInfo[] {
  return conflicts.filter(c => c.exists);
}

/**
 * 사용자 수정이 있는 파일 필터링
 */
export function getUserModifiedFiles(conflicts: ConflictInfo[]): ConflictInfo[] {
  return conflicts.filter(c => c.hasUserModifications);
}

/**
 * 백업 파일 생성
 */
export function createBackup(filePath: string, backupDir?: string): string {
  if (!existsSync(filePath)) {
    throw new Error(`Cannot backup non-existent file: ${filePath}`);
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const fileName = basename(filePath);
  const backupFileName = `${fileName}.backup-${timestamp}`;

  let backupPath: string;

  if (backupDir) {
    mkdirSync(backupDir, { recursive: true });
    backupPath = join(backupDir, backupFileName);
  } else {
    backupPath = join(dirname(filePath), backupFileName);
  }

  copyFileSync(filePath, backupPath);
  return backupPath;
}

/**
 * 안전한 파일 쓰기 (충돌 감지 및 백업 포함)
 */
export function safeWriteFile(
  filePath: string,
  content: string,
  options: WriteOptions = {}
): WriteResult {
  const { force = false, backup = true, backupDir } = options;

  const conflict = checkFileConflict(filePath);
  let backupPath: string | undefined;

  // 파일이 존재하는 경우
  if (conflict.exists) {
    // 사용자 수정이 있고 force가 아닌 경우 건너뛰기
    if (conflict.hasUserModifications && !force) {
      return {
        written: false,
        filePath,
        skipped: true,
        reason: 'File has user modifications. Use --force to overwrite or remove the file first.',
      };
    }

    // 백업 옵션이 켜져 있으면 백업 생성
    if (backup && conflict.hasUserModifications) {
      backupPath = createBackup(filePath, backupDir);
    }
  }

  // 디렉토리 생성 (없으면)
  mkdirSync(dirname(filePath), { recursive: true });

  // 파일 쓰기
  writeFileSync(filePath, content, 'utf-8');

  return {
    written: true,
    filePath,
    backupPath,
  };
}

/**
 * 충돌 보고서 생성
 */
export function generateConflictReport(conflicts: ConflictInfo[]): string {
  const conflictingFiles = getConflictingFiles(conflicts);
  const userModifiedFiles = getUserModifiedFiles(conflicts);

  if (conflictingFiles.length === 0) {
    return 'No conflicts detected. All files are safe to generate.';
  }

  let report = `\n⚠️  CONFLICT DETECTION REPORT\n`;
  report += `${'='.repeat(50)}\n\n`;
  report += `Total files to generate: ${conflicts.length}\n`;
  report += `Existing files: ${conflictingFiles.length}\n`;
  report += `Files with user modifications: ${userModifiedFiles.length}\n\n`;

  if (userModifiedFiles.length > 0) {
    report += `🚨 FILES WITH USER MODIFICATIONS:\n`;
    report += `These files appear to have been manually edited:\n\n`;

    for (const file of userModifiedFiles) {
      report += `  - ${file.filePath}\n`;
    }

    report += `\nOptions:\n`;
    report += `  1. Use --force to overwrite (backup will be created)\n`;
    report += `  2. Use --no-backup --force to overwrite without backup\n`;
    report += `  3. Manually remove or rename the conflicting files\n`;
    report += `  4. Keep existing files and skip generation\n\n`;
  }

  const autoGeneratedFiles = conflictingFiles.filter(c => !c.hasUserModifications);
  if (autoGeneratedFiles.length > 0) {
    report += `✅ AUTO-GENERATED FILES (safe to overwrite):\n`;
    for (const file of autoGeneratedFiles) {
      report += `  - ${file.filePath}\n`;
    }
    report += '\n';
  }

  return report;
}

/**
 * 쿼리키 충돌 감지
 * 동일한 도메인 내에서 같은 키가 생성되는지 확인
 */
export function detectQueryKeyConflicts(
  queryKeys: Record<string, Record<string, string>>
): Array<{ domain: string; key: string; count: number }> {
  const conflicts: Array<{ domain: string; key: string; count: number }> = [];

  for (const [domain, keys] of Object.entries(queryKeys)) {
    const keyCount: Record<string, number> = {};

    for (const key of Object.keys(keys)) {
      keyCount[key] = (keyCount[key] || 0) + 1;
    }

    for (const [key, count] of Object.entries(keyCount)) {
      if (count > 1) {
        conflicts.push({ domain, key, count });
      }
    }
  }

  return conflicts;
}

/**
 * 훅 이름 충돌 감지
 * 동일한 훅 이름이 생성되는지 확인
 */
export function detectHookNameConflicts(
  hookNames: Array<{ domain: string; hookName: string; filePath: string }>
): Array<{ hookName: string; files: string[] }> {
  const hookMap = new Map<string, string[]>();

  for (const { hookName, filePath } of hookNames) {
    if (!hookMap.has(hookName)) {
      hookMap.set(hookName, []);
    }
    hookMap.get(hookName)!.push(filePath);
  }

  const conflicts: Array<{ hookName: string; files: string[] }> = [];

  for (const [hookName, files] of hookMap.entries()) {
    if (files.length > 1) {
      conflicts.push({ hookName, files });
    }
  }

  return conflicts;
}

/**
 * 충돌 요약 출력
 */
export function printConflictSummary(
  fileConflicts: ConflictInfo[],
  queryKeyConflicts: Array<{ domain: string; key: string; count: number }>,
  hookNameConflicts: Array<{ hookName: string; files: string[] }>
): void {
  const userModified = getUserModifiedFiles(fileConflicts);

  if (userModified.length === 0 && queryKeyConflicts.length === 0 && hookNameConflicts.length === 0) {
    console.log('✅ No conflicts detected');
    return;
  }

  console.log('\n⚠️  CONFLICTS DETECTED:');

  if (userModified.length > 0) {
    console.log(`\n📁 Files with user modifications: ${userModified.length}`);
    userModified.forEach(f => console.log(`   - ${f.filePath}`));
  }

  if (queryKeyConflicts.length > 0) {
    console.log(`\n🔑 Duplicate query keys: ${queryKeyConflicts.length}`);
    queryKeyConflicts.forEach(c => {
      console.log(`   - ${c.domain}.${c.key} (appears ${c.count} times)`);
    });
  }

  if (hookNameConflicts.length > 0) {
    console.log(`\n🎣 Duplicate hook names: ${hookNameConflicts.length}`);
    hookNameConflicts.forEach(c => {
      console.log(`   - ${c.hookName}:`);
      c.files.forEach(f => console.log(`     • ${f}`));
    });
  }
}
