/**
 * React Query 훅 생성 메인 로직
 * Bruno 파일들을 읽어서 React Query 훅들을 생성
 */

import { readdirSync, statSync, mkdirSync, writeFileSync } from 'fs';
import { join, relative, dirname } from 'path';
import { parseBrunoFile } from '../parser/bruParser';
import { extractApiFunction } from './apiClientGenerator';
import { generateReactQueryHook } from './reactQueryGenerator';
import { generateQueryKeyFile } from './queryKeyGenerator';
import { generateMSWHandler, generateDomainHandlersIndex, generateMSWIndex } from './mswGenerator';
import {
  checkFileConflict,
  safeWriteFile,
  addAutoGeneratedMarker,
  getUserModifiedFiles,
  detectHookNameConflicts,
  printConflictSummary,
  ConflictInfo,
  WriteOptions,
} from './conflictDetector';

export interface GenerateHooksOptions {
  brunoDir: string;
  outputDir: string;
  axiosInstancePath?: string;
  mswOutputDir?: string; // MSW 핸들러 출력 디렉토리
  force?: boolean; // 기존 파일 덮어쓰기
  backup?: boolean; // 백업 생성 (기본값: true)
  backupDir?: string; // 백업 디렉토리
  dryRun?: boolean; // 실제 파일 생성 없이 충돌 검사만
}

/**
 * Bruno 디렉토리에서 모든 .bru 파일 찾기
 */
function findBrunoFiles(dir: string): string[] {
  const files: string[] = [];

  function traverse(currentDir: string) {
    const entries = readdirSync(currentDir);

    for (const entry of entries) {
      const fullPath = join(currentDir, entry);
      const stat = statSync(fullPath);

      if (stat.isDirectory()) {
        traverse(fullPath);
      } else if (entry.endsWith('.bru')) {
        files.push(fullPath);
      }
    }
  }

  traverse(dir);
  return files;
}

/**
 * 파일 경로에서 도메인 추출
 * "한글명 [EnglishKey]" 형식에서 EnglishKey만 추출
 */
function extractDomain(filePath: string, brunoDir: string): string {
  const relativePath = relative(brunoDir, filePath);
  const parts = relativePath.split('/');
  const folderName = parts[0]; // 첫 번째 폴더가 도메인

  // [키] 패턴 추출
  const match = folderName.match(/\[([^\]]+)\]/);
  if (match) {
    return match[1]; // 대괄호 안의 키만 반환
  }

  return folderName; // 대괄호가 없으면 폴더명 그대로 반환
}

/**
 * React Query 훅 생성
 */
export async function generateHooks(options: GenerateHooksOptions): Promise<void> {
  const {
    brunoDir,
    outputDir,
    axiosInstancePath = '@/utils/axiosInstance',
    mswOutputDir,
    force = false,
    backup = true,
    backupDir,
    dryRun = false,
  } = options;

  const writeOptions: WriteOptions = { force, backup, backupDir };

  console.log('🔍 Searching for .bru files...');
  const brunoFiles = findBrunoFiles(brunoDir);
  console.log(`✅ Found ${brunoFiles.length} .bru files`);

  if (brunoFiles.length === 0) {
    console.log('⚠️  No .bru files found');
    return;
  }

  // Bruno 파일 파싱
  const parsedFiles = brunoFiles.map(filePath => {
    try {
      const parsed = parseBrunoFile(filePath);
      const domain = extractDomain(filePath, brunoDir);
      return { filePath, parsed, domain };
    } catch (error) {
      console.error(`❌ Error parsing ${filePath}:`, error);
      return null;
    }
  }).filter(Boolean) as Array<{ filePath: string; parsed: any; domain: string }>;

  console.log(`📝 Parsed ${parsedFiles.length} files successfully`);

  // 충돌 감지를 위한 사전 분석
  console.log('\n🔍 Checking for conflicts...');

  const queryKeyPath = join(outputDir, 'queryKeys.ts');
  const filesToGenerate: Array<{ path: string; content: string; type: string }> = [];
  const hookInfos: Array<{ domain: string; hookName: string; filePath: string }> = [];

  // Query Keys 파일 준비
  const queryKeyContent = addAutoGeneratedMarker(
    generateQueryKeyFile(
      parsedFiles.map(f => ({ path: f.filePath, parsed: f.parsed, domain: f.domain }))
    )
  );
  filesToGenerate.push({ path: queryKeyPath, content: queryKeyContent, type: 'queryKeys' });

  // 훅 파일들 준비
  const domainDirs = new Set<string>();
  const hooksToGenerate: Array<{
    domain: string;
    domainDir: string;
    hookPath: string;
    content: string;
    hookName: string;
  }> = [];

  for (const { filePath, parsed, domain } of parsedFiles) {
    const apiFunc = extractApiFunction(parsed, filePath);
    if (!apiFunc) {
      console.log(`⚠️  Skipped ${filePath}: Invalid API function`);
      continue;
    }

    const hook = generateReactQueryHook(parsed, apiFunc, domain, axiosInstancePath);
    const domainDir = join(outputDir, domain);
    const hookPath = join(domainDir, hook.fileName);

    domainDirs.add(domainDir);

    // 훅 이름 추출 (파일 내용에서)
    const hookNameMatch = hook.content.match(/export default function (use\w+)/);
    const hookName = hookNameMatch ? hookNameMatch[1] : hook.fileName.replace('.ts', '');

    hookInfos.push({ domain, hookName, filePath: hookPath });
    hooksToGenerate.push({
      domain,
      domainDir,
      hookPath,
      content: addAutoGeneratedMarker(hook.content),
      hookName,
    });
  }

  // 인덱스 파일들 준비
  const indexFilesToGenerate: Array<{ path: string; content: string }> = [];
  for (const domainDir of domainDirs) {
    const domainHooks = hooksToGenerate.filter(h => h.domainDir === domainDir);
    const indexContent = domainHooks
      .map(h => {
        const name = h.hookPath.split('/').pop()?.replace('.ts', '') || '';
        return `export { default as ${name} } from './${name}';`;
      })
      .join('\n') + '\n';

    const indexPath = join(domainDir, 'index.ts');
    indexFilesToGenerate.push({ path: indexPath, content: addAutoGeneratedMarker(indexContent) });
  }

  // 충돌 검사
  const allFilePaths = [
    queryKeyPath,
    ...hooksToGenerate.map(h => h.hookPath),
    ...indexFilesToGenerate.map(f => f.path),
  ];

  const fileConflicts: ConflictInfo[] = allFilePaths.map(checkFileConflict);
  const hookNameConflicts = detectHookNameConflicts(hookInfos);

  // 충돌 요약 출력
  printConflictSummary(fileConflicts, [], hookNameConflicts);

  const userModifiedFiles = getUserModifiedFiles(fileConflicts);

  // Dry run 모드이면 여기서 종료
  if (dryRun) {
    console.log('\n📋 DRY RUN MODE - No files were written');
    console.log(`Would generate ${allFilePaths.length} files`);

    if (userModifiedFiles.length > 0 && !force) {
      console.log(`\n⚠️  ${userModifiedFiles.length} files would be skipped due to user modifications`);
      console.log('Use --force to overwrite these files');
    }
    return;
  }

  // 사용자 수정 파일이 있고 force가 아닌 경우 경고
  if (userModifiedFiles.length > 0 && !force) {
    console.log(`\n🚨 WARNING: ${userModifiedFiles.length} files have user modifications:`);
    userModifiedFiles.forEach(f => console.log(`   - ${f.filePath}`));
    console.log('\nThese files will be SKIPPED. Use --force to overwrite (backups will be created).');
    console.log('Or use --no-backup --force to overwrite without backup.\n');
  }

  // 훅 이름 충돌이 있으면 경고
  if (hookNameConflicts.length > 0) {
    console.log(`\n🚨 WARNING: Duplicate hook names detected:`);
    hookNameConflicts.forEach(c => {
      console.log(`   - ${c.hookName} is used in multiple files:`);
      c.files.forEach(f => console.log(`     • ${f}`));
    });
    console.log('This may cause import conflicts. Consider renaming the Bruno files.\n');
  }

  // 출력 디렉토리 생성
  mkdirSync(outputDir, { recursive: true });

  // Query Keys 파일 생성
  console.log('\n📦 Generating query keys...');
  const queryKeyResult = safeWriteFile(queryKeyPath, queryKeyContent, writeOptions);
  if (queryKeyResult.written) {
    console.log(`✅ Generated: ${queryKeyPath}`);
    if (queryKeyResult.backupPath) {
      console.log(`   📦 Backup: ${queryKeyResult.backupPath}`);
    }
  } else if (queryKeyResult.skipped) {
    console.log(`⏭️  Skipped: ${queryKeyPath}`);
    console.log(`   Reason: ${queryKeyResult.reason}`);
  }

  // 도메인별 훅 생성
  console.log('\n🎣 Generating React Query hooks...');

  for (const domainDir of domainDirs) {
    mkdirSync(domainDir, { recursive: true });
  }

  let generatedCount = 0;
  let skippedCount = 0;
  const backupPaths: string[] = [];

  for (const hook of hooksToGenerate) {
    const result = safeWriteFile(hook.hookPath, hook.content, writeOptions);

    if (result.written) {
      generatedCount++;
      console.log(`✅ Generated: ${hook.hookPath}`);
      if (result.backupPath) {
        backupPaths.push(result.backupPath);
        console.log(`   📦 Backup: ${result.backupPath}`);
      }
    } else if (result.skipped) {
      skippedCount++;
      console.log(`⏭️  Skipped: ${hook.hookPath}`);
      console.log(`   Reason: ${result.reason}`);
    }
  }

  // 인덱스 파일 생성
  console.log('\n📄 Generating index files...');
  for (const indexFile of indexFilesToGenerate) {
    const result = safeWriteFile(indexFile.path, indexFile.content, writeOptions);
    if (result.written) {
      console.log(`✅ Generated: ${indexFile.path}`);
      if (result.backupPath) {
        backupPaths.push(result.backupPath);
      }
    } else if (result.skipped) {
      console.log(`⏭️  Skipped: ${indexFile.path}`);
    }
  }

  // 최종 요약
  console.log('\n✨ Generation complete!');
  console.log(`   Generated: ${generatedCount} hooks`);
  if (skippedCount > 0) {
    console.log(`   Skipped: ${skippedCount} files (use --force to overwrite)`);
  }
  if (backupPaths.length > 0) {
    console.log(`   Backups created: ${backupPaths.length} files`);
  }

  console.log(`\n📂 Output directory: ${outputDir}`);
  console.log('\n📚 Usage example:');
  console.log(`import { useGetApplicationsCompetitors } from './${relative(process.cwd(), join(outputDir, 'applications'))}';\n`);
  console.log(`const { data, isLoading, error } = useGetApplicationsCompetitors();`);

  // MSW 핸들러 생성 (옵션이 제공된 경우)
  if (mswOutputDir) {
    console.log('\n🎭 Generating MSW handlers...');
    await generateMSWHandlers(parsedFiles, mswOutputDir, writeOptions);
  }
}

/**
 * MSW 핸들러 생성
 */
async function generateMSWHandlers(
  parsedFiles: Array<{ filePath: string; parsed: any; domain: string }>,
  mswOutputDir: string,
  writeOptions: WriteOptions = {}
): Promise<void> {
  // MSW 출력 디렉토리 생성
  mkdirSync(mswOutputDir, { recursive: true });

  // 도메인별로 핸들러 그룹화
  const domainHandlers = new Map<string, Array<{ fileName: string; content: string }>>();

  for (const { filePath, parsed, domain } of parsedFiles) {
    const handler = generateMSWHandler(parsed, filePath, domain);

    if (!handler) {
      // done: true 또는 docs 없음
      continue;
    }

    if (!domainHandlers.has(domain)) {
      domainHandlers.set(domain, []);
    }

    domainHandlers.get(domain)!.push({
      fileName: handler.fileName,
      content: addAutoGeneratedMarker(handler.content),
    });
  }

  // 도메인별 디렉토리 및 파일 생성
  const domains: string[] = [];

  for (const [domain, handlers] of domainHandlers.entries()) {
    domains.push(domain);

    // 도메인 디렉토리 생성
    const domainDir = join(mswOutputDir, domain);
    mkdirSync(domainDir, { recursive: true });

    // 각 핸들러 파일 작성
    const handlerInfos: Array<{ fileName: string; handlerName: string }> = [];

    for (const handler of handlers) {
      const handlerPath = join(domainDir, handler.fileName);
      const result = safeWriteFile(handlerPath, handler.content, writeOptions);

      if (result.written) {
        console.log(`✅ MSW Generated: ${handlerPath}`);
        if (result.backupPath) {
          console.log(`   📦 Backup: ${result.backupPath}`);
        }
      } else if (result.skipped) {
        console.log(`⏭️  MSW Skipped: ${handlerPath}`);
        console.log(`   Reason: ${result.reason}`);
      }

      handlerInfos.push({
        fileName: handler.fileName,
        handlerName: handler.fileName.replace('.ts', ''),
      });
    }

    // 도메인별 index 파일 생성
    const domainIndexContent = addAutoGeneratedMarker(generateDomainHandlersIndex(domain, handlerInfos));
    const domainIndexPath = join(domainDir, 'index.ts');
    const indexResult = safeWriteFile(domainIndexPath, domainIndexContent, writeOptions);
    if (indexResult.written) {
      console.log(`✅ MSW Index Generated: ${domainIndexPath}`);
    } else if (indexResult.skipped) {
      console.log(`⏭️  MSW Index Skipped: ${domainIndexPath}`);
    }
  }

  // 전체 handlers index 파일 생성
  if (domains.length > 0) {
    const mswIndexContent = addAutoGeneratedMarker(generateMSWIndex(domains));
    const mswIndexPath = join(mswOutputDir, 'handlers.ts');
    const mainIndexResult = safeWriteFile(mswIndexPath, mswIndexContent, writeOptions);

    if (mainIndexResult.written) {
      console.log(`✅ MSW Main Index Generated: ${mswIndexPath}`);
    } else if (mainIndexResult.skipped) {
      console.log(`⏭️  MSW Main Index Skipped: ${mswIndexPath}`);
    }

    console.log(`\n🎭 MSW handlers generated successfully!`);
    console.log(`📂 MSW Output directory: ${mswOutputDir}`);
    console.log(`\n📚 Usage example:`);
    console.log(`import { handlers } from './${relative(process.cwd(), mswIndexPath).replace('.ts', '')}';\n`);
    console.log(`const worker = setupWorker(...handlers);`);
  } else {
    console.log(`ℹ️  No MSW handlers generated (all files have done: true or missing docs)`);
  }
}
